nelmio_api_doc:
    documentation:
        info:
            title: App Back API
            description: Backend Symfony DDD centre sur User avec JWT, outbox, Mercure et Stripe.
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc)
